# Form implementation generated from reading ui file 'F:\qt_test\SSH\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 830)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 830))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 830))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 700))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.video = QtWidgets.QLabel(parent=self.widget_3)
        self.video.setMinimumSize(QtCore.QSize(100, 0))
        self.video.setObjectName("video")
        self.gridLayout_2.addWidget(self.video, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 67, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.startButton.setMinimumSize(QtCore.QSize(200, 60))
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        spacerItem1 = QtWidgets.QSpacerItem(114, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.WQbookButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.WQbookButton.setMinimumSize(QtCore.QSize(200, 60))
        self.WQbookButton.setObjectName("WQbookButton")
        self.horizontalLayout.addWidget(self.WQbookButton)
        self.dictationButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.dictationButton.setEnabled(False)
        self.dictationButton.setMinimumSize(QtCore.QSize(200, 60))
        self.dictationButton.setObjectName("dictationButton")
        self.horizontalLayout.addWidget(self.dictationButton)
        spacerItem2 = QtWidgets.QSpacerItem(114, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.settingButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.settingButton.setMinimumSize(QtCore.QSize(200, 60))
        self.settingButton.setObjectName("settingButton")
        self.horizontalLayout.addWidget(self.settingButton)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.video.setBuddy(self.video)

        self.retranslateUi(MainWindow)
        self.startButton.clicked.connect(MainWindow.startBC) # type: ignore
        self.WQbookButton.clicked.connect(MainWindow.WQbBC) # type: ignore
        self.settingButton.clicked.connect(MainWindow.settingBC) # type: ignore
        self.dictationButton.clicked.connect(MainWindow.dictationBC) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.video.setText(_translate("MainWindow", "等待画面"))
        self.startButton.setText(_translate("MainWindow", "开始"))
        self.WQbookButton.setText(_translate("MainWindow", "错题本"))
        self.dictationButton.setText(_translate("MainWindow", "听写"))
        self.settingButton.setText(_translate("MainWindow", "设置"))
