# Form implementation generated from reading ui file 'F:\qt_test\SSH\ui\TimeRunOutWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TimeRunOutWindow(object):
    def setupUi(self, TimeRunOutWindow):
        TimeRunOutWindow.setObjectName("TimeRunOutWindow")
        TimeRunOutWindow.resize(267, 196)
        self.gridLayout = QtWidgets.QGridLayout(TimeRunOutWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=TimeRunOutWindow)
        self.label.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=TimeRunOutWindow)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 105, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(TimeRunOutWindow)
        QtCore.QMetaObject.connectSlotsByName(TimeRunOutWindow)

    def retranslateUi(self, TimeRunOutWindow):
        _translate = QtCore.QCoreApplication.translate
        TimeRunOutWindow.setWindowTitle(_translate("TimeRunOutWindow", "Form"))
        self.label.setText(_translate("TimeRunOutWindow", "   超时!"))
        self.label_2.setText(_translate("TimeRunOutWindow", "        已向管理员发送消息,窗口将自动关闭"))
