# Form implementation generated from reading ui file 'F:\qt_test\SSH\ui\WQbWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WQbWindow(object):
    def setupUi(self, WQbWindow):
        WQbWindow.setObjectName("WQbWindow")
        WQbWindow.resize(1453, 929)
        WQbWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout_3 = QtWidgets.QGridLayout(WQbWindow)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=WQbWindow)
        self.widget.setMinimumSize(QtCore.QSize(400, 800))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=WQbWindow)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=WQbWindow)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=WQbWindow)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(parent=WQbWindow)
        self.widget_2.setMinimumSize(QtCore.QSize(900, 0))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.WQ = QtWidgets.QLabel(parent=self.widget_2)
        self.WQ.setMinimumSize(QtCore.QSize(0, 600))
        self.WQ.setObjectName("WQ")
        self.gridLayout.addWidget(self.WQ, 0, 0, 1, 1)
        self.description = QtWidgets.QTextEdit(parent=self.widget_2)
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(WQbWindow)
        self.pushButton.clicked.connect(WQbWindow.addItemBC) # type: ignore
        self.listWidget.itemClicked['QListWidgetItem*'].connect(WQbWindow.itemC) # type: ignore
        self.pushButton_3.clicked.connect(WQbWindow.deleteBC) # type: ignore
        self.pushButton_2.clicked.connect(WQbWindow.editBC) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WQbWindow)

    def retranslateUi(self, WQbWindow):
        _translate = QtCore.QCoreApplication.translate
        WQbWindow.setWindowTitle(_translate("WQbWindow", "WQbWindow"))
        self.pushButton.setText(_translate("WQbWindow", "新建"))
        self.pushButton_2.setText(_translate("WQbWindow", "编辑"))
        self.pushButton_3.setText(_translate("WQbWindow", "删除"))
        self.WQ.setText(_translate("WQbWindow", "等待加载"))
